src/main/java/com/coretechies/veepropbeta/domain/Faq.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.coretechies.veepropbeta.domain;

import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.validator.constraints.NotBlank;

/**
 *
 * @author Noppp
 */
@Entity
@Table(name = "faq")
@Access(AccessType.FIELD)
public class Faq {
    
    @Id
    @GenericGenerator(name = "faq", strategy = "increment")
    @GeneratedValue(generator = "faq")
    private Integer faqId;
    
    @Column
    private Integer adminId;
    
    @Column 
    @NotBlank(message = "Please Enter Question")
    private String question;
    
    @Column
    @NotBlank(message = "Please Enter Answer")
    private String answer;

    public Integer getFaqId() {
        return faqId;
    }

    public void setFaqId(Integer faqId) {
        this.faqId = faqId;
    }

    public Integer getAdminId() {
        return adminId;
    }

    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    @Override
    public String toString() {
        return "faq{" + "faqId=" + faqId + ", adminId=" + adminId + ", question=" + question + ", answer=" + answer + '}';
    }
    
    
}

src/main/java/com/coretechies/veepropbeta/domain/User.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.coretechies.veepropbeta.domain;

import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.validator.constraints.NotBlank;

/**
 *
 * @author Arvind
 */
@Entity
@Table(name="user")
@Access(AccessType.FIELD)
public class User {
    
    @Id
    @GenericGenerator(name="user",strategy ="increment" )
    @GeneratedValue(generator = "user")
    private Integer IdentificationNumber;
    
    @Column
    private String name;
    
    @Column
    private String email;
    
    @Column
    private String contact;
    
    @Column
    private Integer securityQuestionId;
    
    @Column
    private String securityAnswer;
    
    @Column
    private Integer gender;
    
    @Column
    @Temporal(TemporalType.DATE)
    private Date dateOfBirth;
    
    @Column
    private String image;
    
    @Column
    private Integer userStatus;
    
    @Column
    @Temporal(TemporalType.DATE)
    private Date registrationDate;
    
    @Column
    private String screenName;
    
    @Column
    private String officeTelNo;
    
    @Column
    private String homeTelNo;
    
    @Column
     private String faxNo;
    
    @Column 
    private String PassportNo;
    
    @Column
    private String residentCountry;
    
    

    public Integer getIdentificationNumber() {
        return IdentificationNumber;
    }

    public void setIdentificationNumber(Integer IdentificationNumber) {
        this.IdentificationNumber = IdentificationNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public Integer getSecurityQuestionId() {
        return securityQuestionId;
    }

    public void setSecurityQuestionId(Integer securityQuestionId) {
        this.securityQuestionId = securityQuestionId;
    }

    public String getSecurityAnswer() {
        return securityAnswer;
    }

    public void setSecurityAnswer(String securityAnswer) {
        this.securityAnswer = securityAnswer;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Integer getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    public Date getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    public String getOfficeTelNo() {
        return officeTelNo;
    }

    public void setOfficeTelNo(String officeTelNo) {
        this.officeTelNo = officeTelNo;
    }

    public String getHomeTelNo() {
        return homeTelNo;
    }

    public void setHomeTelNo(String homeTelNo) {
        this.homeTelNo = homeTelNo;
    }

    public String getFaxNo() {
        return faxNo;
    }

    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo;
    }

    public String getPassportNo() {
        return PassportNo;
    }

    public void setPassportNo(String PassportNo) {
        this.PassportNo = PassportNo;
    }

    public String getResidentCountry() {
        return residentCountry;
    }

    public void setResidentCountry(String residentCountry) {
        this.residentCountry = residentCountry;
    }

   
    

    @Override
    public String toString() {
        return "User{" + "IdentificationNumber=" + IdentificationNumber + ", name=" + name + ", email=" + email + ", contact=" + contact + ", securityQuestionId=" + securityQuestionId + ", securityAnswer=" + securityAnswer + ", gender=" + gender + ", dateOfBirth=" + dateOfBirth + ", image=" + image + ", userStatus=" + userStatus + ", registrationDate=" + registrationDate + ", screenName=" + screenName + ", officeTelNo=" + officeTelNo + ", homeTelNo=" + homeTelNo + ", faxNo=" + faxNo + ", PassportNo=" + PassportNo + ", residentCountry=" + residentCountry + '}';
    }
    
    

   
    
    
    
    
}

src/main/java/com/coretechies/veepropbeta/domain/VeeCreditTransaction.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.coretechies.veepropbeta.domain;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 *
 * @author Arvind
 */
@Entity
@Table(name="veecredittransaction")
@Access(AccessType.FIELD)
public class VeeCreditTransaction {
    
    @Id
    @GenericGenerator(name = "veecredittransaction", strategy = "increment")
    @GeneratedValue(generator = "veecredittransaction")
    private Integer VeeCreditTransactionId;
    
    @Column
    private Integer veeCreditTransactionToken;
            
    @Column
    private Double veeCredit;
            
    @Column
    private String remark;
            
    @Column 
    private Integer transactionStatus;
      
    @Column
    private Integer VeeCreditTransactionType;
    
    @Column
    private String fileName;
    
    @Column
    private String bankTransactionId;

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getBankTransactionId() {
        return bankTransactionId;
    }

    public void setBankTransactionId(String bankTransactionId) {
        this.bankTransactionId = bankTransactionId;
    }

    public Integer getVeeCreditTransactionId() {
        return VeeCreditTransactionId;
    }

    public void setVeeCreditTransactionId(Integer VeeCreditTransactionId) {
        this.VeeCreditTransactionId = VeeCreditTransactionId;
    }

    public Integer getVeeCreditTransactionToken() {
        return veeCreditTransactionToken;
    }

    public void setVeeCreditTransactionToken(Integer veeCreditTransactionToken) {
        this.veeCreditTransactionToken = veeCreditTransactionToken;
    }

    public Double getVeeCredit() {
        return veeCredit;
    }

    public void setVeeCredit(Double veeCredit) {
        this.veeCredit = veeCredit;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getTransactionStatus() {
        return transactionStatus;
    }

    public void setTransactionStatus(Integer transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    public Integer getVeeCreditTransactionType() {
        return VeeCreditTransactionType;
    }

    public void setVeeCreditTransactionType(Integer VeeCreditTransactionType) {
        this.VeeCreditTransactionType = VeeCreditTransactionType;
    }

    @Override
    public String toString() {
        return "VeeCreditTransaction{" + "VeeCreditTransactionId=" + VeeCreditTransactionId + ", veeCreditTransactionToken=" + veeCreditTransactionToken + ", veeCredit=" + veeCredit + ", remark=" + remark + ", transactionStatus=" + transactionStatus + ", VeeCreditTransactionType=" + VeeCreditTransactionType + ", fileName=" + fileName + ", bankTransactionId=" + bankTransactionId + '}';
    }
    
}

src/main/java/com/coretechies/veepropbeta/web/controller/FeedbackController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.coretechies.veepropbeta.web.controller;

import com.coretechies.veepropbeta.domain.Feedback;
import com.coretechies.veepropbeta.domain.Login;
import com.coretechies.veepropbeta.domain.Notification;
import com.coretechies.veepropbeta.service.feedback.FeedBackService;
import com.coretechies.veepropbeta.service.notification.NotificationService;
import com.coretechies.veepropbeta.web.controller.algorithm.UserRole;
import java.util.List;
import javax.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.servlet.ModelAndView;
/**
 *
 * @author Rohit
 */
@Controller
@SessionAttributes("user")
public class FeedbackController {
    
    private final Logger logger= LoggerFactory.getLogger(getClass());
    
    @Autowired
    private FeedBackService feedbackservice;
    
    @Autowired
    private NotificationService notificationService;
    
     @RequestMapping(value = "/feedback",method = RequestMethod.GET)
     public ModelAndView addfeedback(@ModelAttribute("feedback") Feedback feedback, ModelMap model){
         Login user = (Login)model.get("user");
         if(user != null && user.getUserRole().equals(UserRole.TRADER.getUserRoleValue())){
            List<Notification> notifications = notificationService.retreiveNotification(user.getIdentificationNumber());
            model.addAttribute("notification", notifications);             
             return new ModelAndView("feedback");
         }
         return new ModelAndView("redirect:/login");
     }
     
     @RequestMapping(value ="/feedback",method = RequestMethod.POST)
     public ModelAndView Savefeedback(@Valid @ModelAttribute("feedback")Feedback feedback,BindingResult result,ModelMap model){
         Login user = (Login) model.get("user");         
         if(user != null && user.getUserRole().equals(UserRole.TRADER.getUserRoleValue())){
            if(result.hasErrors()){
               return new ModelAndView("feedback");
            }
            List<Notification> notifications = notificationService.retreiveNotification(user.getIdentificationNumber());
            model.addAttribute("notification", notifications);              
            feedbackservice.saveFeedBack(feedback,user.getIdentificationNumber());
            model.addAttribute("message", "Feedback added successfully....");
            return new ModelAndView("feedback");
         }
         return  new ModelAndView("redirect:/login");
     }
}

src/main/java/com/coretechies/veepropbeta/web/controller/NotificationController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.coretechies.veepropbeta.web.controller;


import com.coretechies.veepropbeta.domain.Login;
import com.coretechies.veepropbeta.domain.Notification;
import com.coretechies.veepropbeta.domain.Transaction;
import com.coretechies.veepropbeta.service.notification.NotificationService;
import com.coretechies.veepropbeta.service.transaction.TransactionService;
import com.coretechies.veepropbeta.web.controller.algorithm.TransactionType;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.servlet.ModelAndView;

/**
 *
 * @author Noppp
 */
@Controller
@SessionAttributes({"user"})
public class NotificationController {
    
    private final Logger logger = LoggerFactory.getLogger(getClass());
    
    @Autowired
    private TransactionService transactionService;
    
    @Autowired
    private NotificationService notificationService;
    
    @RequestMapping(value = "/notification/{transactionId}/{transactionType}/{notificationId}", method = RequestMethod.GET)
    public ModelAndView showNotification(@PathVariable Integer transactionId,
            @PathVariable Integer transactionType,@PathVariable Integer notificationId,ModelMap model){
        Login user = (Login) model.get("user");
        if(user != null){
            notificationService.updateNotification(notificationId);
            Notification notification = notificationService.retreiveNotificationById(notificationId);
            model.addAttribute("notification",notification.getNotification());
            List<Notification> notificationList = notificationService.retreiveNotification(user.getIdentificationNumber());
            model.addAttribute("notificationList", notificationList);
            
            model.addAttribute("transactionDate", "Transaction Performed on : "+notification.getNotificationDate());
            if(transactionId > 0){
                Transaction transaction = transactionService.retrieveTransaction(transactionId);
                if(transactionType == TransactionType.VEECREDITTRANSACTION.getTransactionTypeValue()){
                    model.addAttribute("vCredit","vCredit Transacted : "+transaction.getAmount());
                }else if(transactionType == TransactionType.SHARETRADINGTRANSACTION.getTransactionTypeValue()){
                        model.addAttribute("vCredit","Share Traded of : "+transaction.getAmount()+" USD");
                }else if(transactionType == TransactionType.BONUSTRANSACTION.getTransactionTypeValue()){
                    model.addAttribute("vCredit","Bonus Recieved "+transaction.getAmount()+" USD");
                }
            }else if(transactionId == 0){
                model.addAttribute("vCredit","Title updated, for complete detail check title upgradation rules.");
            }else if(transactionId == -1){
                model.addAttribute("vCredit","Level updated, for complete detail check Level upgradation rules.");
            }else if(transactionId == -2){
                model.addAttribute("vCredit","Profile Updated");
            }
            return new ModelAndView("notification");
        }
        return new ModelAndView("redirect:/login");
    }
}

src/main/webapp/WEB-INF/view/disputedata.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Veeprop</title>
        <link rel="stylesheet" href="/veepropbeta/css/reset.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/veepropbeta/css/style_admin.css" type="text/css" media="screen" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans|Baumans' rel='stylesheet' type='text/css'>
        <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>

        <style>
            table tr th, table tbody tr td {
                border: 1px black solid;
                padding: 0 20px;
            }
            table tr {
                border: 1px black solid;
            }
            table {
                border: 1px black solid;
                text-align: center;
            }
        </style>
    </head>

    <body>
        <section id="spacer">
            <p>Veeprop Moderator Panel</p>
            <div style="    margin-left: 1200px;margin-top: 16px;padding-top: 20px;color: #000;"><a href="/veepropbeta/logout" style="margin-left: 30px;">Sign Out</a></div>
        </section>
        <section id="text_column_admin">
            <section id="boxcontent_admin">
                <div class="sell_board"><span class="sb">Moderator Tasks [${name}]</span></div>
                <div class="ctg"><span class="ctg_p">Daily Task</span></div>  
                
                <article class="link_grp">
                    <ul>
                        <li><a href="/veepropbeta/home">Overview</a></li>
                        <li><a href="/veepropbeta/pendingshare">View Share Transaction</a></li>
                        <li><a href="/veepropbeta/pendingvcredit">Pending vCredit Transaction</a></li>
                        <li><a href="/veepropbeta/pendingprofiles">Pending Profile Upgrade Request</a></li>
                        <li><a href="/veepropbeta/introduce">Binary Tree</a></li>
                        <li><a href="/veepropbeta/home">Block Player</a></li>
                        <li><a href="/veepropbeta/disputecases">Complaints</a></li>
                    </ul>
                </article>
                
                <div class="ctg"><span class="ctg_p">Moderator Profile</span></div>
                
                <article class="link_grp">
                    <ul>
                        <li><a href="/veepropbeta/moderator/profile/0">Profile</a></li>
                        <li><a href="/veepropbeta/moderator/profile/1">Edit Profile</a></li>
                        <li>Report Problem</li>
                    </ul>
                </article>
                
                <br class="clear"/>
            </section>
            
            <article class="column1">                
                <br class="clear"/>
                <div style="  margin-top: 20px; ">
                    <table style="float: left;">
                        <caption style="font-weight: bold;">Dispute Data Request</caption>
                        <tr>
                            <th>Seller ID</th>
                            <td>${dispute.sellerIN}</td>
                        </tr>
                        <tr>
                            <th>Seller Name</th>
                            <td>${dispute.sellerName}</td>
                        </tr>
                        <tr>
                            <th>Buyer ID</th>
                            <td>${dispute.buyerIN}</td>
                        </tr>
                        <tr>
                            <th>Vee Credit</th>
                            <td>${dispute.veeCreditAmount}</td>
                        </tr>
                        <tr>
                            <th>Account Number</th>
                            <td>${dispute.sellerAcountNumber}</td>
                        </tr>
                        <tr>
                            <th>Seller Email</th>
                            <td>${dispute.sellerEmail}</td>
                        </tr>
                        <tr>
                            <th>Seller Contact</th>
                            <td>${dispute.sellerContactNumber}</td>
                        </tr>
                        <tr>
                            <th>Proof of Transaction</th>
                            <td><a href="/veepropbeta/${dispute.proofOfTransaction}" target="_blank" style="color:blue;">check</a></td>
                        </tr>
                        <tr>
                            <th>Reason for Dispute</th>
                            <td style="max-width: 200px;">${dispute.reason}</td>
                        </tr>
                    </table>
                    <table style="float: left; margin-left: 10px;">
                        <caption style="font-weight: bold;">Data According to System</caption>
                        <tr>
                            <th>Seller ID</th>
                            <td>${transaction.sellerIN}</td>
                        </tr>
                        <tr>
                            <th>Seller Name</th>
                            <td>${seller.name}</td>
                        </tr>
                        <tr>
                            <th>Buyer ID</th>
                            <td>${transaction.buyerIN}</td>
                        </tr>
                        <tr>
                            <th>Vee Credit</th>
                            <td>${transaction.amount}</td>
                        </tr>
                        <tr>
                            <th>Account Number</th>
                            <td>${sellerBank.accountNumber}</td>
                        </tr>
                        <tr>
                            <th>Seller Email</th>
                            <td>${seller.email}</td>
                        </tr>
                        <tr>
                            <th>Seller Contact</th>
                            <td>${seller.contact}</td>
                        </tr>
                        <tr>
                            <th>Action</th>
                            <td style="color: blue; text-decoration: underline;">
                                <a href="/veepropbeta/dispute/decline/${dispute.veeCreditTransactionId}">Decline</a>
                                <a href="/veepropbeta/dispute/accept/${dispute.veeCreditTransactionId}" style="padding-left: 20px;">Accept</a>
                            </td>
                    </table>
                            <br />
                    <p style="color: red;float: left; margin-top: 20px; ">Decline In Case dispute data request entry do
                    not match with data in system or data is insufficient according to you.</p>
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                    <p style="color: red;float: left; margin-top: 20px; ">Accept in Case dispute data request entry
                         match with data in system and according to you data is sufficient & correct.</p>
                </div>
            </article>
        </section>
    </body>
</html>

src/main/webapp/WEB-INF/view/makeprofit.jsp
<%-- 
    Document   : contact
    Created on : Jan 29, 2014, 4:39:42 PM
    Author     : CoreTechies
--%>
  <%@page contentType="text/html" pageEncoding="windows-1252"%> 
  <%@ taglib prefix="c"  uri="http://java.sun.com/jsp/jstl/core" %>
  <%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
 
<html>
 <head>
  <title>How Makes Profits</title>
     <link rel="stylesheet" href="/veepropbeta/css/style.css" type="text/css" media="screen" />
     <link href="/veepropbeta/css/lightbox.css" rel="stylesheet" />
     <link href='http://fonts.googleapis.com/css?family=Open+Sans|Baumans' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" href="/veepropbeta/css/bootstrap-responsive.css" type="text/css" media="screen" />
     <link rel="stylesheet" href="/veepropbeta/css/bootstrap-responsive.min.css" type="text/css" media="screen" />
     <link rel="stylesheet" href="/veepropbeta/css/bootstrap.css" type="text/css" media="screen" />
     <link rel="stylesheet" href="/veepropbeta/css/bootstrap.min.css" type="text/css" media="screen" />
    
 </head>      
  <body>
      <%@include file="header.jsp" %>
      <%@include file="Lotinformation.jsp" %>
        
           <div class="row">
               <a  class="list-group-item active"><center><b>How Makes Profits</b></center></a>
               <h1  class="col-md-5 offset3">Page under Construction.....</h1>
          </div>
    
      <%@include file="footer.jsp" %>      
</body>
</html>

src/main/webapp/WEB-INF/view/moderatortree.jsp
<!DOCTYPE HTML>
<html>
    <head>
        <title>Veeprop</title>
        <link rel="stylesheet" href="css/reset.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="css/style_admin.css" type="text/css" media="screen" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans|Baumans' rel='stylesheet' type='text/css'>
        <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/veepropbeta/css/tree.css" />

<script type="text/javascript">
	function extend(id){
            var url = "/veepropbeta/retrieveChild/"+id+"/";
            $.get(url, function(data) {
                if(data){
                    var len = data.length;
                    if(len===4){
                        if(data[0]===null){
                            var html = '<li><a>+</a></li>'
                                                 +'<li><a id="'+data[2]+'" onclick="return extend(this.id);">'+data[3]+'</a><ul class="'+data[2]+'"></ul></li>';
                            $('.'+id).html(html);
                        }else{
                            var html = '<li><a id="'+data[0]+'" onclick="return extend(this.id);">'+data[1]+'</a><ul class="'+data[0]+'"></ul></li>'
                                                 +'<li><a id="'+data[2]+'" onclick="return extend(this.id);">'+data[3]+'</a><ul class="'+data[2]+'"></ul></li>';
                            $('.'+id).html(html);
                        }
                    }else if(len===2){
                            var html = '<li><a id="'+data[0]+'" onclick="return extend(this.id);">'+data[1]+'</a><ul class="'+data[0]+'"></ul></li>'
                                                 +'<li><a>+</a></li>';
                            $('.'+id).html(html);

                    }else{
                        var html = '<li><a>+</a></li>'
                        +'<li><a>+</a></ul></li>';
                        $('.'+id).html(html);
                    }
                }else{
                    var html = '<li><a>+</a></li>'
		 			 +'<li><a>+</a></ul></li>';
		 $('.'+id).html(html);
                }
            });
	}
</script>        
    </head>

    <body>
        <section id="spacer">
            <p>Veeprop Moderator Panel</p>
            <div style="    margin-left: 1200px;margin-top: 16px;padding-top: 20px;color: #000;"><a href="/veepropbeta/logout" style="margin-left: 30px;">Sign Out</a></div>
        </section>
        <section id="text_column_admin">
            <section id="boxcontent_admin">
                <div class="sell_board"><span class="sb">Moderator Tasks [${name}]</span></div>
                <div class="ctg"><span class="ctg_p">Daily Task</span></div>  
                
                <article class="link_grp">
                    <ul>
                        <li><a href="/veepropbeta/home">Overview</a></li>
                        <li><a href="/veepropbeta/pendingshare">View Share Transaction</a></li>
                        <li><a href="/veepropbeta/pendingvcredit">Pending vCredit Transaction</a></li>
                        <li><a href="/veepropbeta/pendingprofiles">Pending Profile Upgrade Request</a></li>
                        <li><a href="/veepropbeta/introduce">Binary Tree</a></li>
                        <li><a href="/veepropbeta/home">Block Player</a></li>
                        <li><a href="">Complaints</a></li>
                    </ul>
                </article>
                
                <div class="ctg"><span class="ctg_p">Moderator Profile</span></div>
                
                <article class="link_grp">
                    <ul>
                        <li>Profile</li>
                        <li>Edit Profile</li>
                        <li>Report Problem</li>
                    </ul>
                </article>
                
                <br class="clear"/>
            </section>
            
            <article class="column1">
                <h3>
                    Binary Tree of System
                </h3>

                <br class="clear"/>
                <div class="tree" style="  margin-top: 20px; ">
                <ul>
                    <li>
                            <a id="${userInfo.identificationNumber}" onclick="return extend(this.id);"> ${userInfo.name}</a>
                        <ul class="${userInfo.identificationNumber}"></ul>
                    </li>
                </ul>
                </div>
            </article>
        </section>
    </body>
</html>